In [12]:
import pandas as pd

In [13]:
df = pd.read_csv("../data_cleaned/clean.csv")
df.head()

,source_file,text
0,/linux-data/projects/ioe_purwanchal_campus_iic...,यसरी व्यवस्थापन गर्दैछ बिपी कोइराला क्यान्सर अ...
1,/linux-data/projects/ioe_purwanchal_campus_iic...,प्रत्यारोपणमा उपयोग हुने वस्तु सरकारी फार्मेसी...
2,/linux-data/projects/ioe_purwanchal_campus_iic...,मेचीनगरमा ‘अफ्रिकन स्वाइन फ्लू’ र ‘लम्पी स्किन...
3,/linux-data/projects/ioe_purwanchal_campus_iic...,अलपत्र भएका आधारभूत अस्पताल साउनबाटै सञ्चालनमा...
4,/linux-data/projects/ioe_purwanchal_campus_iic...,कालीमाटीमा भित्रिएका १७४ प्रकारका तरकारीमा विषादी

In [14]:
df.drop(columns=["source_file"], inplace=True)

In [15]:
df

                                                     text
0       यसरी व्यवस्थापन गर्दैछ बिपी कोइराला क्यान्सर अ...
1       प्रत्यारोपणमा उपयोग हुने वस्तु सरकारी फार्मेसी...
2       मेचीनगरमा ‘अफ्रिकन स्वाइन फ्लू’ र ‘लम्पी स्किन...
3       अलपत्र भएका आधारभूत अस्पताल साउनबाटै सञ्चालनमा...
4       कालीमाटीमा भित्रिएका १७४ प्रकारका तरकारीमा विषादी
...                                                   ...
744145    कर्माचार्य ग्रुपको बिस्कुटदेखि तेलसम्मका कोसेली
744146  म्याग्दी पर्यटन सूचना केन्द्रमा कोसेली घर संञ्...
744147       मह सिकारको सिजन सुरु हुँदा नहुँदै कोसेली माग
744148           रामलाई ससुरालीबाट चाँदीको तिरधनुष कोसेली
744149           रामलाई ससुरालीबाट चाँदीको तिरधनुष कोसेली

[744150 rows x 1 columns]

In [16]:
df.to_csv("../data_cleaned/clean.csv", index=False)